apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: prometheus-config
    files: 
    - prometheus/prometheus.yaml
resources:
- prometheus/deployment.yaml
- prometheus/service.yaml
- prometheus/auth.yaml
- metrics-server/deployment.yaml
- metrics-server/service.yaml
- metrics-server/apiservice.yaml
- metrics-server/auth.yaml
- kube-state-metrics/deployment.yaml
- kube-state-metrics/service.yaml
- kube-state-metrics/auth.yaml
