


---  
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: failuremanager
spec:
  controller: nginx-ingress.failure.svc/api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: failuremanager-ingress
#    annotations:
#    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: failuremanager
  rules:
  - http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: failuremanager
            port:
              number: 5002
      - path: /insufficientcpu
        pathType: Prefix
        backend:
          service:
            name: failuremanager
            port:
              number: 5002