
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubow-user  # This user must be in the deployments that use K8s API
rules:
- apiGroups: ["apps", ""]
  resources:
  - deployments
  - pods
  - events
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubow-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubow-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubow-user
subjects:
- kind: ServiceAccount
  name: kubow-user
  namespace: default  

